version: 2.1


jobs:  
  deployment-and-api-tests:    
    build: # name of your job
    machine: # executor type
      image: ubuntu-2004:202010-01
    steps:   
      - checkout  
      - run:
          name: 'Intro'
          command:
            'echo testing all examples in /examples against test suite in /test'     
      - run:
          name: Deploy Mockoon for BB API and PyTest 
          command: cd mock/examples && docker-compose up --build -d
      - run:
          name: Check Status of Mockoon and API-Testing Containers
          command: docker ps
      - run:
          name: Testing APIs
          command: 'echo testing using containers' 
      - run:
          name: Check Status if Testing Containers are Deployed 
          command: docker ps
      - run:
          name: Run Cucumber tests against BB Mock Server using Mockoon
          command: docker  exec -i pytest  pytest 
                
                

    
workflows:  
  deployment-and-api-tests:    
    jobs:      
      - deployment-and-api-tests:
          filters:            
            branches:
              only:
                - main
